spring.datasource.url=jdbc:mysql://localhost:3306/url_shortener_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=girnare1164@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Cloud Redis Configuration
spring.data.redis.host="https://sought-guppy-88753.upstash.io"
spring.data.redis.port=6379
spring.data.redis.password=gQAAAAAAAVqxAAIgcDI0ODVkY2Q4OWNiZGY0ZWU0YTU2OTk3MTZjNzU0ZjUxNQ
spring.data.redis.ssl.enabled=true
